Script started on 2023-10-27 15:18:39-06:00 [TERM="xterm-256color" TTY="/dev/pts/8" COLUMNS="127" LINES="18"]
[?2004h]0;mark_marchan@KamiMaku: ~/cse113/prelab07[01;32mmark_marchan@KamiMaku[00m:[01;34m~/cse113/prelab07[00m$ make
[?2004lgcc -g -Wall fundamental.c -o f
gcc -g -Wall array.c -o a
gcc -g -Wall swap.c -o s
[?2004h]0;mark_marchan@KamiMaku: ~/cse113/prelab07[01;32mmark_marchan@KamiMaku[00m:[01;34m~/cse113/prelab07[00m$ ./f
[?2004lAddress of P: 0x7fff9f558838 
Value of P: 2.718280
Address of pointer: 0x7fff9f558838
Value of pointer: 2.718280
[?2004h]0;mark_marchan@KamiMaku: ~/cse113/prelab07[01;32mmark_marchan@KamiMaku[00m:[01;34m~/cse113/prelab07[00m$ ./a
[?2004la = 1 2 3 4 5 6 7 8 9 10

b = 10 10 10 10 10 10 10 10 10 10

after incrementing
a = 2 3 4 5 6 7 8 9 10 11
2 3 4 5 6 7 8 9 10 11

a = a + b
a = 12 13 14 15 16 17 18 19 20 21

b remains unchanged
b = 10 10 10 10 10 10 10 10 10 10
[?2004h]0;mark_marchan@KamiMaku: ~/cse113/prelab07[01;32mmark_marchan@KamiMaku[00m:[01;34m~/cse113/prelab07[00m$ ./s
[?2004lbefore swap: a = 6	b = 9
in function swap: a = 9	b = 6
after swap: a = 9	b = 6
[?2004h]0;mark_marchan@KamiMaku: ~/cse113/prelab07[01;32mmark_marchan@KamiMaku[00m:[01;34m~/cse113/prelab07[00m$ exit
[?2004lexit

Script done on 2023-10-27 15:18:57-06:00 [COMMAND_EXIT_CODE="0"]
