Script started on Wed Aug 23 15:47:54 2023
[1m[7m%[27m[1m[0m                                                                                ]7;file://The-Dingus-Book.local/Users/eliasvargas/desktop/CSE%20113/Lab%200[0m[27m[24m[Jeliasvargas@The-Dingus-Book Lab 0 % [K[?2004hgcc -g -Wall ascii.c -o ascii[16Dname.c -o nam   [13Dascii.c -o ascii[29D                             [29Dgcc -g -Wall ascii.c -o ascii[?2004l
[1m[7m%[27m[1m[0m                                                                                ]7;file://The-Dingus-Book.local/Users/eliasvargas/desktop/CSE%20113/Lab%200[0m[27m[24m[Jeliasvargas@The-Dingus-Book Lab 0 % [K[?2004h../ascii[?2004l
 ^.  .^      /
 /__/_______/
   /       /
  /       /
[1m[7m%[27m[1m[0m                                                                                ]7;file://The-Dingus-Book.local/Users/eliasvargas/desktop/CSE%20113/Lab%200[0m[27m[24m[Jeliasvargas@The-Dingus-Book Lab 0 % [K[?2004heexit[?2004l

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

Script done on Wed Aug 23 15:48:10 2023
