Script started on Wed Aug 23 15:20:45 2023
[1m[7m%[27m[1m[0m                                                                                                 [0m[27m[24m[Jeliasvargas@The-Dingus-Book Lab 0 % [K[?2004hggcc -g --Wall     wall     Wall -o hello        hello.c -o hello[?2004l
[1m[7m%[27m[1m[0m                                                                                                 [0m[27m[24m[Jeliasvargas@The-Dingus-Book Lab 0 % [K[?2004h..\. ... ./jell   j  . ./hello[?2004l
Hello, world!
[1m[7m%[27m[1m[0m                                                                                                 [0m[27m[24m[Jeliasvargas@The-Dingus-Book Lab 0 % [K[?2004heexit[?2004l

Script done on Wed Aug 23 15:21:21 2023
