Script started on Wed Aug 23 15:36:02 2023
[1m[7m%[27m[1m[0m                                                                                                 [0m[27m[24m[Jeliasvargas@The-Dingus-Book Lab 0 % [K[?2004hexit./hellogcc -g -Wall hello.c -o hello              name.c -o name[?2004l
[1m[7m%[27m[1m[0m                                                                                                 [0m[27m[24m[Jeliasvargas@The-Dingus-Book Lab 0 % [K[?2004h../ n name[?2004l
EEEEEEEEEEEE   LLLLL        IIIII    !!!
EEEEEEEEEEEE   LLLLL        IIIII    !!!
EEEE           LLLLL        IIIII    !!!
EEEE           LLLLL        IIIII    !!!
EEEEEEEEEE     LLLLL        IIIII    !!!
EEEEEEEEEE     LLLLL        IIIII    !!!
EEEE           LLLLL        IIIII       
EEEEEEEEEEEEE  LLLLLLLLLL   IIIII    !!!
EEEEEEEEEEEEE  LLLLLLLLLL   IIIII    !!!
[1m[7m%[27m[1m[0m                                                                                                 [0m[27m[24m[Jeliasvargas@The-Dingus-Book Lab 0 % [K[?2004heexit[?2004l

Script done on Wed Aug 23 15:36:16 2023
