Script started on Sun Oct 15 18:48:16 2023
[1m[7m%[27m[1m[0m                                                                                                                                                                                                   [0m[27m[24m[Jeliasvargas@Eliass-MacBook-Air lab5 % [K[?2004hggcc-  -g -Wall lab5_q2.c -o lab5_q2[?2004l
[1m[7m%[27m[1m[0m                                                                                                                                                                                                   [0m[27m[24m[Jeliasvargas@Eliass-MacBook-Air lab5 % [K[?2004h../lab5
[Jlab5*          lab5.dSYM/     lab5_q2*       lab5_q2.dSYM/[A[0m[27m[24m[38C./lab5[K_q2[?2004l
[JRED: 18 
ORANGE: 19 
YELLOW: 5 
GREEN: 6 
BLUE: 7 
INDIGO: 14 
VIOLET: 15 
[1m[7m%[27m[1m[0m                                                                                                                                                                                                   [0m[27m[24m[Jeliasvargas@Eliass-MacBook-Air lab5 % [K[?2004heexit[?2004l

Script done on Sun Oct 15 18:48:37 2023
