Script started on Mon Oct  9 15:13:14 2023
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                 [0m[27m[24m[Jeliasvargas@Eliass-MacBook-Air lab2 % [K[?2004hggcc -g -g  g -Wall pp8.c -o - pp8[?2004l
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                 [0m[27m[24m[Jeliasvargas@Eliass-MacBook-Air lab2 % [K[?2004h../pp8[?2004l
Please enter a 24-hour time in hours and minutes (HH MM): 
11 20  30
Closest departure time is 11:19am, arriving at 1:31pm. 
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                 [0m[27m[24m[Jeliasvargas@Eliass-MacBook-Air lab2 % [K[?2004h./pp8[?2004l
Please enter a 24-hour time in hours and minutes (HH MM): 
15 30
Closest departure time is 3:45pm, arriving at 5:55pm. 
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                 [0m[27m[24m[Jeliasvargas@Eliass-MacBook-Air lab2 % [K[?2004h./pp8[?2004l
Please enter a 24-hour time in hours and minutes (HH MM): 
19 20
Closest departure time is 7:00pm, arriving at 9:20pm. 
[1m[7m%[27m[1m[0m                                                                                                                                                                                                                                 [0m[27m[24m[Jeliasvargas@Eliass-MacBook-Air lab2 % [K[?2004heexit[?2004l

Script done on Mon Oct  9 15:13:43 2023
