Script started on Wed Nov  8 20:42:35 2023
[1m[7m%[27m[1m[0m                                                                                                                                                                [0m[27m[24m[Jeliasvargas@Eliass-MacBook-Air lab7 % [K[?2004hs mmake all   [?2004l
make: Nothing to be done for `all'.
[1m[7m%[27m[1m[0m                                                                                                                                                                [0m[27m[24m[Jeliasvargas@Eliass-MacBook-Air lab7 % [K[?2004hd ----  lleaks --ate Exit --  ./lab7[?2004l
lab7(5059) MallocStackLogging: could not tag MSL-related memory as no_footprint, so those pages will be included in process footprint - (null)
lab7(5059) MallocStackLogging: recording malloc and VM allocation stacks using lite mode
the length of "c run, c run unix, run unix run" is 31
s1 = c run, c run unix, run unix run
s1 = c run, c run unix, run unix run
s1 = c run, c run unix, run unix run, go c, go!
comparing:
c run, c run unix, run unix run
and
look c, look c
strings differ in the first 14 chars; cmp = 1

comparing:
look c, look c
and
look c, go c!
strings are the same for 8 chars; cmp = 0

comparing:
look c, look c
and
, go c, go!
strings differ in the first 9 chars; cmp = 1
c run, c run unix, run unix run
searching for x in "c run, c run unix, run unix run"
x is located at address 0x16f233210
which is 16 bytes from the base address 0x16f233200
searching for a in "c run, c run unix, run unix run"
a is located at address 0x0
which is -6159544832 bytes from the base address 0x16f233200
c run, c run unix, run unix run
reversed is
nur xinu nur ,xinu nur c ,nur c
Process 5059 is not debuggable. Due to security restrictions, leaks can only show or save contents of readonly memory of restricted processes.

Process:         lab7 [5059]
Path:            /Users/USER/Desktop/*/lab7
Load Address:    0x100bcc000
Identifier:      lab7
Version:         0
Code Type:       ARM64
Platform:        macOS
Parent Process:  leaks [5058]

Date/Time:       2023-11-08 20:42:59.429 -0700
Launch Time:     2023-11-08 20:42:59.379 -0700
OS Version:      macOS 13.2.1 (22D68)
Report Version:  7
Analysis Tool:   /usr/bin/leaks

Physical footprint:         2849K
Physical footprint (peak):  2849K
Idle exit: untracked
----

leaks Report Version: 4.0, multi-line stacks
Process 5059: 225 nodes malloced for 17 KB
Process 5059: 0 leaks for 0 total leaked bytes.

[1m[7m%[27m[1m[0m                                                                                                                                                                [0m[27m[24m[Jeliasvargas@Eliass-MacBook-Air lab7 % [K[?2004heexit[?2004l

Script done on Wed Nov  8 20:43:01 2023
